# Day 2: Mathematical Operations and Elementary Functions

## Reference

- Julia document: [Mathematical Operations and Elementary Functions](https://docs.julialang.org/en/v1/manual/mathematical-operations/)

In [81]:
using Printf
using FITSIO
using PyPlot
using PyCall

- There is an inverse divide

In [4]:
5 / 6 == 6 \ 5 

true

- Division truncated to an integer

In [7]:
5 ÷ 6

0

- Instead of `x ** 2` in Python, Julia uses `^` for power

In [14]:
5 ^ 2

25

- A numeric literal placed directly before an identifier or parentheses

In [15]:
x = 5
2x == 2 * x

true

- Julia's promotion system makes arithmetic operations on mixtures of argument types "just work" naturally and automatically.

In [17]:
2 / 5

0.4

- `false` acts like a "strong zero"

In [19]:
false * NaN 

0.0

In [20]:
false * -Inf

-0.0

- `xor` bitwise operation 

In [22]:
xor(0, 1)

1

In [23]:
0 ⊻ 1

# Type \xor + Tab

1

### Vectorized dot operator

In [27]:
[1, 2, 3] .^ 2

3-element Vector{Int64}:
 1
 4
 9

In [30]:
√5

2.23606797749979

In [31]:
.√[1, 2, 3]

3-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772

- Can also use the `@.` macro

In [32]:
x = [1, 2, 3]
y = [4, 5, 6]

@. 2x^2 + 3y

3-element Vector{Int64}:
 14
 23
 36

In [36]:
@. x += y

3-element Vector{Int64}:
 5
 7
 9

- Note the dot syntax is also applicable to user-defined operators.

### Numerical comparison

- `isequal`, `isfinite`, `isinf`, `isnan` functions

In [38]:
isnan(NaN)

true

In [39]:
isinf(Inf)

true

In [40]:
isfinite(-Inf)

false

In [41]:
0.0 == -0.0

true

In [42]:
isequal(0.0, -0.0)

false

### Elementary functions

- Can also be vectorized

In [43]:
sin.(x)

3-element Vector{Float64}:
 -0.9589242746631385
  0.6569865987187891
  0.4121184852417566

### Numerical conversion

In [44]:
Int8(130)

LoadError: InexactError: trunc(Int8, 130)

In [45]:
Int32(2.4)

LoadError: InexactError: Int32(2.4)

In [46]:
Int(127)

127

In [47]:
127 % Int

127

### Rounding

In [49]:
round(2.4)

2.0

In [50]:
floor(2.4)

2.0

In [51]:
ceil(2.4)

3.0

In [52]:
trunc(2.4)

2.0

In [54]:
trunc(Int8, 12.2)

12

In [55]:
trunc(Int8, 129)

LoadError: InexactError: trunc(Int8, 129)

### Sign and absolute value functions

In [56]:
abs(-2)

2

In [57]:
abs2(-3.14)

9.8596

In [58]:
sign(-0.0)

-0.0

In [60]:
sign(5)

1

### Power, logs, and roots

In [61]:
∛3

1.4422495703074083

In [63]:
√2

1.4142135623730951

In [64]:
log(2)

0.6931471805599453

In [65]:
log10(10)

1.0

In [66]:
exp(2)

7.38905609893065

In [70]:
hypot(-2, 3)

3.605551275463989

### Trigonometric and hyperbolic functions

In [79]:
sin(π / 2)

1.0

- Use the `d` version for degrees

In [75]:
sind(90.)

1.0

In [77]:
cosd(30.)

0.8660254037844386

- `atan` accepts two arguments corresponding to a traditional `atan2` function.
    - `atan2(y,x)` is the argument (also called phase or angle) of the complex number `x+iy`

In [80]:
atan(2.0, 1.0)

1.1071487177940904

## Experiment on FITS file

In [82]:
fits_file = FITS("/Users/song/Dropbox/work/project/huoguo/huoguo/data/M51.fits"); 

img = FITSIO.read(fits_file[1]);

In [181]:
function cart2polar(x, y)
    return hypot.(x, y), atan.(y, x)
end


function polar2cart(r, θ)
    return r .* cos.(θ), r .* sin.(θ)
end

polar2cart (generic function with 1 method)

In [113]:
x = y = 0:1:99; 

In [120]:
@time cart2polar(x, y)

  0.000022 seconds (3 allocations: 1.781 KiB)


([0.0, 1.4142135623730951, 2.8284271247461903, 4.242640687119285, 5.656854249492381, 7.0710678118654755, 8.48528137423857, 9.899494936611665, 11.313708498984761, 12.727922061357855  …  127.27922061357856, 128.69343417595164, 130.10764773832474, 131.52186130069785, 132.93607486307093, 134.35028842544403, 135.7645019878171, 137.17871555019022, 138.59292911256333, 140.0071426749364], [0.0, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483  …  0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483])

In [116]:
r, θ = cart2polar(x, y)

([0.0, 1.4142135623730951, 2.8284271247461903, 4.242640687119285, 5.656854249492381, 7.0710678118654755, 8.48528137423857, 9.899494936611665, 11.313708498984761, 12.727922061357855  …  127.27922061357856, 128.69343417595164, 130.10764773832474, 131.52186130069785, 132.93607486307093, 134.35028842544403, 135.7645019878171, 137.17871555019022, 138.59292911256333, 140.0071426749364], [0.0, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483  …  0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483, 0.7853981633974483])

In [117]:
xx, yy = polar2cart(r, θ)

([0.0, 1.0000000000000002, 2.0000000000000004, 3.0, 4.000000000000001, 5.000000000000001, 6.0, 7.000000000000001, 8.000000000000002, 9.0  …  90.00000000000001, 91.0, 92.0, 93.00000000000001, 94.0, 95.00000000000001, 96.0, 97.0, 98.00000000000001, 99.0], [0.0, 1.0, 2.0, 2.9999999999999996, 4.0, 5.0, 5.999999999999999, 6.999999999999999, 8.0, 8.999999999999998  …  90.0, 90.99999999999999, 91.99999999999999, 93.0, 93.99999999999999, 95.0, 95.99999999999999, 96.99999999999999, 98.0, 98.99999999999999])

In [130]:
@time polar2cart(r, θ)

  0.000011 seconds (3 allocations: 1.781 KiB)


([0.0, 1.0000000000000002, 2.0000000000000004, 3.0, 4.000000000000001, 5.000000000000001, 6.0, 7.000000000000001, 8.000000000000002, 9.0  …  90.00000000000001, 91.0, 92.0, 93.00000000000001, 94.0, 95.00000000000001, 96.0, 97.0, 98.00000000000001, 99.0], [0.0, 1.0, 2.0, 2.9999999999999996, 4.0, 5.0, 5.999999999999999, 6.999999999999999, 8.0, 8.999999999999998  …  90.0, 90.99999999999999, 91.99999999999999, 93.0, 93.99999999999999, 95.0, 95.99999999999999, 96.99999999999999, 98.0, 98.99999999999999])

In [154]:
(n, m) = size(img); 

In [162]:
@time d = [cart2polar(x - 256., y - 256.) for x in 0:(m-1), y in 0:(n-1)]

  0.175630 seconds (65.37 k allocations: 7.600 MiB, 79.68% compilation time)


512×512 Matrix{Tuple{Float64, Float64}}:
 (362.039, -2.35619)   (361.332, -2.35815)   …  (361.332, 2.35815)
 (361.332, -2.35424)   (360.624, -2.35619)      (360.624, 2.35619)
 (360.627, -2.35227)   (359.918, -2.35423)      (359.918, 2.35423)
 (359.924, -2.3503)    (359.213, -2.35226)      (359.213, 2.35226)
 (359.221, -2.34832)   (358.509, -2.35028)      (358.509, 2.35028)
 (358.521, -2.34633)   (357.807, -2.34829)   …  (357.807, 2.34829)
 (357.821, -2.34434)   (357.106, -2.34629)      (357.106, 2.34629)
 (357.123, -2.34233)   (356.407, -2.34429)      (356.407, 2.34429)
 (356.427, -2.34032)   (355.709, -2.34228)      (355.709, 2.34228)
 (355.732, -2.3383)    (355.013, -2.34026)      (355.013, 2.34026)
 (355.038, -2.33628)   (354.318, -2.33823)   …  (354.318, 2.33823)
 (354.346, -2.33424)   (353.624, -2.3362)       (353.624, 2.3362)
 (353.655, -2.3322)    (352.932, -2.33415)      (352.932, 2.33415)
 ⋮                                           ⋱  
 (353.655, -0.809394)  (352.932, -0.8074

In [214]:
function imgPolarCoord(img)
    (n, m) = size(img)
    xid = (0:m-1)' .* ones(n) .- n / 2
    yid = ones(m)' .* (0:n-1) .- m / 2
    
    return hypot.(xid, yid), atan.(yid, xid)
end

imgPolarCoord (generic function with 1 method)

In [262]:
function cart2polar(x, y)
    return hypot(x, y), atan(y, x)
end

function imgPolarCoord2(img)
    (n, m) = size(img)
    return [cart2polar.(x - n/2, y - m/2) for x in 0:(m-1), y in 0:(n-1)]
end

imgPolarCoord2 (generic function with 1 method)

In [265]:
@time pcoord = imgPolarCoord2(img);

  0.010415 seconds (2 allocations: 4.000 MiB)


In [264]:
@time r, θ = imgPolarCoord(img);

  0.012975 seconds (13 allocations: 8.008 MiB)


In [266]:
data = zeros(1000, 1000); 

In [269]:
@time r, θ = imgPolarCoord(data);

  0.039558 seconds (13 allocations: 30.533 MiB)


In [270]:
@time pcoord = imgPolarCoord2(data);

  0.046224 seconds (2 allocations: 15.259 MiB, 15.74% gc time)
